### ISSUE TITLE
Set response headers.

### ISSUE THREAD

**Issue by brennonbrimhall** [espadrine/sc#31]
Is there a way to set response headers so we can solve badges/shields#221?  

In reading through [/doc/Readme.md](https://github.com/espadrine/sc/blob/master/doc/Readme.md), I was able to find a reference to an Ask object, stating that an instance of an Ask object has the member res, of type [http.ServerResponse](http://nodejs.org/api/http.html#http_class_http_serverresponse), which in turn has method [writeHead()](http://nodejs.org/api/http.html#http_response_writehead_statuscode_reasonphrase_headers), which seems to do the trick.  How does one go about getting an instance of the Ask object to interrogate it?  Can we beef the documentation up on this point please?

**Comment by jankeromnes** [comment]
The documentation was updated, and the issue badges/shields#221 was fixed by @espadrine. @brennonbrimhall can you please have a look again and tell us if the docs are better now?

**Comment by jankeromnes** [comment]
Let's say this is fixed now.

To set response headers, you can either use the `ask` object like so: (see also shields example)

    camp.route(/^\/path\/?/, function (data, match, end, ask) {
      ask.res.setHeader('X-Header-Name', 'header-value');
    });

Or use a middleware to set headers on every request, like so:

    camp.handle(function (request, response, next) {
      response.setHeader('X-Header-Name', 'header-value');
      next();
    });
