### ISSUE TITLE
Add License To Project

### ISSUE THREAD

**Issue by kopelli** [espadrine/sc#38]
I'd love to use this for a quick reference project at work, but unfortunately we have to make sure we're only using approved licensed material. Since there's no license listed in the project, I can't use it.

Please add one or more of the following:

* A LICENSE.md file with the appropriate license
* A section in the README.md with the appropriate license
* Something on the project's page with the appropriate license

**Comment by espadrine** [comment]
Thanks for pointing this out! I hope you are satisfied with this change.

**Comment by kopelli** [comment]
Thanks! One of those things that's easy to overlook, and also easy to fix.
