### ISSUE TITLE
Use HSTS when `secure` option is `true`.

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/sc#39]
When you create a Camp server with:

    var app = camp.start({
      secure: true, // ...
    });

it would be great if that secure server automatically sends the [Strict-Transport-Security](https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security) header (like in [this example](https://aaronblohowiak.telegr.am/blog_posts/setting-up-ssl-hsts-and-an-http-https-redirec)).

**Comment by jankeromnes** [comment]
Context: For my [Janitor](https://github.com/jankeromnes/janitor) app, I create a secure HTTPS server, and I permanently redirect any HTTP traffic to HTTPS via a forwarding server (see [the code](https://github.com/jankeromnes/janitor/blob/master/app.js)). Using an HSTS header, as @espadrine suggested, would harden such a scheme.

Supporting this in Camp would also make [The File Tree](https://github.com/garden/tree), which uses the same scheme, benefit from HSTS for free.

**Comment by espadrine** [comment]
It is too sneaky to do it for `secure: true`. We can have an `hsts: true`, though.

Some applications may have a piece of the website under HTTP, and another piece (the sensitive part, such as login or payment) under HTTPS. Figuring out why, and that you have no recourse, would not be very appealing.

**Comment by jankeromnes** [comment]
Or maybe there is a way to define a response header that should always be sent? E.g. `camp.start({ secure: true, headers: {'Strict-Transport-Security': 'etc'} })`

**Comment by espadrine** [comment]
That sounds like a good idea!

**Comment by espadrine** [comment]
How about having a `server.request(function(ask) { ask.res.setHeader('Strict-Transport-Security': maxAge); })`?

I envision the most generic unit, artfully called `genericUnit`, which catches the request (and then has to call `ask.end()`) if it returns true, otherwise it simply modifies every request before they get caught.

**Comment by jankeromnes** [comment]
To me "handler" is not explicit enough about the fact that it handles *all* requests *before* other handlers / routes / units / things.

Looking forward to the test though :)

**Comment by espadrine** [comment]
I'll document it!

**Comment by jankeromnes** [comment]
I'd like to bikeshed the name, so I'll suggest other options soon :)

Also, it could be used to verify that a user is logged in (and redirect to the right place if not) before any other route. In some code of mine, I have to do something like `if (user.signedin()) { ... } else { ... }` in every route, factoring this out would be great!

**Comment by espadrine** [comment]
I expected you would figure out that use-case!

**Comment by espadrine** [comment]
Bikeshedding time?
