### ISSUE TITLE
How to proxy websockify request?

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/sc#41]
I'm writing a proxy for a noVNC instance running on another server, using ScoutCamp.

I was able to proxy all HTTPS traffic with something like:

    app.route(/^\/vnc(\/.*)$/, function (data, match, end, query) {
      var options = { hostname: 'localhost', path: path.normalize(match[2]) };
      var proxy = http.request(options, function (res) {
        query.res.writeHead(res.statusCode, res.headers);
        res.pipe(query.res, {end: true});
      });
      query.req.pipe(proxy, {end: true});
    });

However, there is a request to `wss://janitor.technology/websockify` that I can't proxy.

I tried using:
-  `app.route(/^\/websockify/, function () {})`, but that doesn't get called when the request has the header `Upgrade: websocket`
- `app.ws('websockify', function () {})`, but that translates to `janitor.technology/$websocket:websockify` instead of `janitor.technology/websockify`

Any ideas how I could proxy the websockify request? Shouldn't my `app.route` get called even if there is a `Upgrade: websocket` header? Should I use `require('ws')` directly instead of Camp?

**Comment by espadrine** [comment]
Ideally, you want to make the request to `wss://janitor.technology/websockify` be `wss://janitor.technology/$websocket:websockify`. Otherwise, you can reset the stack to change the websocket catcher: https://github.com/espadrine/sc/tree/master/doc#the-stack.

**Comment by jankeromnes** [comment]
Actually, I didn't need to change noVNC's websocket URI, nor edit the Camp stack (but thanks for the documentation link anyway! it was helpful), because I just used `app.on('upgrade')` to catch all websocket requests and proxy them in https://github.com/jankeromnes/janitor/commit/1d077c3d2811e9762eef75036dad5d46146903ed.
