### ISSUE TITLE
Server-Sent Event bug?

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/sc#42]
Shouldn't the line https://github.com/espadrine/sc/blob/ba6f0080e02b97e968f831ac63c6b73a63ab543d/lib/camp.js#L442 have `join('\ndata:')` instead of `join('\ndata')`? (Note the missing `:`).

Probably never hit because the "usual" path goes through emitting a `JSON.stringify()`ed message, but I guess anyone can call `source.emit()` or `source.sendSSE()` directly.

**Comment by jankeromnes** [comment]
Also, imagine that Camp's Server-Sent Events are used to stream large quantities of logs. It looks like for each `source`, `source.history` will continue to accumulate data forever, and that `sources` will continue to accumulate new `source`s forever.

Maybe there is a way around the bigger memory leaks, by supporting Server-Sent Event sources without history or IDs, and also a way to delete old sources? (And maybe also an optional "self-destroy-on-no-clients" feature).

**Comment by jankeromnes** [comment]
Additional thought, it seems that `source.lastMsgId === source.history.length` is always true, but it might allow doing something like `source.history = []` if its data becomes too large, and every should hopefully continue to work as before (without the old data).

**Comment by jankeromnes** [comment]
Also, #42 \o/

**Comment by jankeromnes** [comment]
Note: It's possible to hack the current API not to keep any history:

    var source = app.eventSource('channelID');
    source.history = { length: 0; push: function(){} }; // No history shall be kept in this fake Array.

**Comment by espadrine** [comment]
> (Note the missing :).

Good catch!

> It looks like for each source, source.history will continue to accumulate data forever

Let's make a new issue for that. Here are my initial thoughts.

It is pretty much unavoidable to prevent the user from losing data upon a disconnection. However, we can allow the user to set a limit, by adding an `options` parameter to `server.eventSource(channel)`, with a `histSize` field, defaulting to infinity. If the history is full, we can send an empty `id` to reset it and empty it, conforming to the spec. (If the histSize is 0, we can skip sending the `id` altogether.)

Whether we implement that or not, we should detect whether clients have received a message. We should delete messages that we have sent if no client has had their connection dropped within 15 seconds after the message is written.
