### ISSUE TITLE
Improve certificate detection

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/sc#54]
You recently added this code to detect certificates:

```js
var KEY_HEADER = '-----BEGIN RSA PRIVATE KEY-----\n';
var CERT_HEADER = '-----BEGIN CERTIFICATE-----\n';
```

This doesn't work when certificates use `\r\n` as line endings. Even worse, it logs `Error: ENOENT: no such file or directory, open '-----BEGIN RSA PRIVATE KEY-----` followed by your private key in plain text.

Please remove the `\n` from both headers.

**Comment by espadrine** [comment]
Excellent point. I don't know where the official standard for the format is, but I made a better regex.

**Comment by jankeromnes** [comment]
Reopening because the CA detection is still broken:

```js
camp.start({
  /* ... */
  ca: ['-----BEGIN CERTIFICATE-----...']
}
```

causes this error:

```
CA file not found: -----BEGIN CERTIFICATE-----...
```

This is currently causing https://janitor.technology to show a security warning on Chrome.

**Comment by jankeromnes** [comment]
Can be fixed trivially by correcting the typo in lib/camp.js line 950 by replacing the line

```js
if (file.slice(0, CERT_HEADER.length) === CERT_HEADER) {
```

with

```js
if (CERT_HEADER.test(file)) {
```

(can't open pull requests right now, public mac that's too old for GH edit or Cloud9)
