### ISSUE TITLE
Relative template paths in `Camp.template(paths)`?

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/sc#59]
I tried to use `Camp.template()` with relative file paths like `'../templates/header.html'`, but https://github.com/espadrine/sc/blob/master/lib/camp.js#L288 tries to read the path relative to where the `camp.js` file is installed.

Maybe instead it should read template paths relative to `process.cwd()`?

**Comment by jankeromnes** [comment]
To clarify, passing `'../templates/header.html'` will look for `header.html` in `./node_modules/camp/templates/`, which doesn't exist (and doesn't make sense).

**Comment by espadrine** [comment]
I made a directory in which I `npm install /path/to/master` (ce2ecd826d3786918c6b707856212beda5fc541b). I made two files:

serve.js 

```js
let sc = require('camp')
let t = sc.template('hello')
t({name:'Jan'}).pipe(process.stdout)
```

hello

```
How are you {{= name}}?
```

Performing `node serve.js` yielded, as intended, "How are you Jan?".

So, I believe this bug is fixed.

**Comment by jankeromnes** [comment]
Thank you for testing this! And sorry for filing what's actually not a camp bug. I figured out what I did wrong:

hello

lib/serve.js

```js
let sc = require('camp')
let t = sc.template('../hello') // here I mistakenly had an extra '../'
t({name:'Yann'}).pipe(process.stdout)
```

app.js

```js
require('./lib/serve');
```

Running `node app.js` gives:

```
fs.js:583
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '../hello'
    at Object.fs.openSync (fs.js:583:18)
    at Object.fs.readFileSync (fs.js:490:33)
    at Object.template (/home/ubuntu/temp/node_modules/camp/lib/camp.js:298:26)
    at Object.<anonymous> (/home/ubuntu/temp/lib/serve.js:2:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
```

The reason I had the extra `../` in my `../templates/<x>` paths was that the previous templating system (with `camp.route()` and the `end()` callback) based relative paths on `./web/`, whereas the new system bases paths straight on `./`. Furthermore, I came to wrong conclusions because I forgot that previous templates were based on `./web/`, and thought instead that they were based on the current module path, i.e. `./lib/`.
