### ISSUE TITLE
Please publish new version to npm

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/sc#61]
For [janitor](https://github.com/JanitorTechnology/janitor), we had to [temporarily](https://github.com/JanitorTechnology/janitor/commit/a8df359f058c5480cbd730c089f9478ae0df5397) [fork](https://www.npmjs.com/package/@jankeromnes/camp) ScoutCamp because we needed a few features that weren't available upstream.

I believe these features have since been implemented, i.e.:
- e6b5a5da8b2a41e9702410af3815b372b48e56f7 A `res.json(data, replacer, space)` helper to send JSON responses
- a5ff54b566cfd24462be2070fe623d897daa8ecb Method-specific `app.{get,post,put,patch,delete}` routing helpers
- 7b19564760370d05725ddf2928cc3ed3553ddc29 An option to save consumed request data chunks for later use (e.g. proxies)

Please publish a new version of ScoutCamp to npm, so that these features become available. This will allow us to "unfork" ScoutCamp in Janitor.

**Comment by espadrine** [comment]
New version published. https://github.com/espadrine/sc/commit/1fae41be4ecb3e2b0453038db0e7adf82143d475
