### ISSUE TITLE
Enable greenkeeper.io service, auto-update vulnerable packages

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/sc#66]
For https://github.com/JanitorTechnology/janitor and https://github.com/JanitorTechnology/selfapi we enabled the https://greenkeeper.io integration a while ago, and we're very happy with it (it automatically opens pull requests to upgrade dependencies in `package.json` when newer versions are available).

For `sc`, it would, for example, automatically open a pull request to upgrade `ws` from the current (vulnerable*) version to the latest (safe) version `4.0.0`. And if it passes the tests, you can simply merge these PRs anytime a package is upgraded. Easy peasy! 🌴 

* We also use the https://snyk.io dependency, which tells you if some dependencies are vulnerable. And it turns out that there is a DDoS vulnerability in `ws`, versions `<1.1.5` or `>=2.0.0 <3.3.1`.

**Comment by jankeromnes** [comment]
@espadrine If you make me a project collaborator/admin, I can do that for you. 😄

**Comment by espadrine** [comment]
You already are a project collaborator!

I'd like to review all patches though.

**Comment by jankeromnes** [comment]
@espadrine Being a project collaborator doesn't allow me to enable Greenkeeper, [only an owner or admin can do that](https://greenkeeper.io/faq.html#owners-only).

Please add me as a project owner or admin, or enable https://greenkeeper.io on https://github.com/espadrine/sc/.

Then, Greenkeeper will open pull requests when package updates are available, and you'll be able to review all these patches (and also verify that they pass the tests on Travis).

**Comment by espadrine** [comment]
> Please add me as a project owner or admin

I was going to, but I couldn't find a way. Reading the Greenkeeper doc further:

> Giving Greenkeeper these permissions can only be done by an admin of the organisation. Having admin rights to an individual repo in an organisation is not sufficient.

Looks like I cannot do that for sc specifically, and since it is under espadrine (a _user_, not an organization), I cannot do that at the (non-existent) organization level either (or at least I didn't find a way).

Instead, I added Greenkeeper to the sc repo by authenticating myself.

**Comment by jankeromnes** [comment]
Perfect, thanks!
